require("awful.autofocus")
require("aturan.mulai")
require("aturan.kebiasaan")
require("aturan.tugas")
-- require("aturan.tugas-kiri")
require("kendali.mouse")
require("kendali.keyboard")
require("aturan.kerja")
require("tampilan.desktop")
require("tampilan.jendela")
